Tweak to compile with Apple Clang v13.0
macos-11 Apple Clang does not support -Wno-unused-but-set-variable

To fix CI

error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]